# Configuracion del servidor
server.port=5000

# Logging
logging.level.mx.edu.utez.paqueteria=INFO
logging.level.com.google.firebase=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# AWS Configuration
aws_access_key_id=ASIAXYKJUFO5PVMZHWJL
aws_secret_access_key=A0F+Xca0NLQUd91kw4UOTj9DJKCD44Fr4Q4X0DqA
aws_session_token=IQoJb3JpZ2luX2VjEKb//////////wEaCXVzLXdlc3QtMiJGMEQCICJV768MIIH6fS8yqyy0xa0W77sMvSAvkpD62JMtjZPeAiApq9mcnslD7S4oFmTJ/USwUHFCUutfADWtWsiPbJWQjyqwAghvEAAaDDUzMzI2NzIyOTYyNiIMyZqlMI0YafLkNrXhKo0CMd7o0HFYwi50JYp/BSPcM4BtLNGfb02xSlW4cQdmiZuY5hnVnHqpyWAfRWNZ2RDGSlpPs3N5qCbE1wXqo/WYAfyLFC2Wu91YLXyz6dW20m3VeUbTEhi5AnVDEKkI05P93qhZWUPglp5ANLN0hqFqg7toe3bIQZPatYqyw0bZRZiPG1Cv2sNiH2xGqaHZGXZSOZGyK8QSx+3g46Xr2UZS97xMxjY3oCk6z/zMRjjV7FbD/5u0gF5qkGgKIGZX4k8SxJuN9PKtfYt+rlFni/WZxTsI2ST4DTrVVOf1sBMYwaxZCe9/DZa5mPTcjs40BItW4ZsVUV5cmdGll7T8YT8PZMb7YX4Ev/37WWabJVUwxI7PyQY6ngFBzkeACHNG4p8sQJ+Uz9u9a034ACiFA3errV3i/IdsaRdXOuUPJtWOhG9SAVuCWNWh4EIBbr/N3dpgNK8GGQHB+QiT5tOPbIwzDfQd6wpQLshhcfTJIKj+161O/IBYI1XIzcIC6+TTk6ieDkA8aj4HWXRCzvEVU85n1ZeIhrwbgzEtgix+BvS6KJJJnVG2MqxoDsfQPrn7rugsLcN1CA==
aws.s3.region=us-east-1
aws.s3.bucket=paqueteria-10-a

logging.level.com.amazonaws.internal.InstanceMetadataServiceResourceFetcher=OFF
logging.level.com.amazonaws.internal.EC2ResourceFetcher=OFF

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
